# Required to connect to your outgoing mail server. Example for using gmail:
# gmail
SMTP_SERVER: smtp-mail.outlook.com
SMTP_PORT: 587
USERNAME: monadressemail@hotmail.fr
PASSWORD: "mon_mot_de_passe"

TIMEZONE: 'US/Pacific'

PARTICIPANTS:
  - LaÃ«titia <5605@holbertonstudents.com>
  - BenoÃ®t <fleur-a-fleur59@hotmail.fr>
  - Nicole <carolinechochoy@aol.com>


# Warning -- if you mess this up you could get an infinite loop
DONT-PAIR:
  - XX, YY   # XX and YY are married
  - XXX, YYY   # XXX and YYY are best friends

# From address should be the organizer in case participants have any questions
FROM: Caro <fleur-a-fleur59@hotmail.fr>

# Both SUBJECT and MESSAGE can include variable substitution for the 
# "santa" and "santee"
SUBJECT: Tu es le secret santa de {santee}
MESSAGE: |

  ðŸŽ„ Ho Ho Ho, {santa} ! ðŸŽ…

  Câ€™est cette pÃ©riode magique de lâ€™annÃ©e oÃ¹ nos poches sont lÃ©gÃ¨res, mais nos cÅ“urs lourdsâ€¦ de rire ! PrÃ©pare-toi pour notre incroyable Secret Santa, oÃ¹ la rÃ¨gle dâ€™or est de ne pas dÃ©passer 5â‚¬. Oui, vous avez bien lu, moins que le prix d'une pinte de biÃ¨re au Gabo !

  Tu es le Secret Santa de {santee}

  Option 1 : Trouve quelque chose de mignon et joyeux Ã  moins de 5â‚¬. Un dÃ©fi pour ta crÃ©ativitÃ© et ton sens de lâ€™Ã©conomie !

  Option 2 : Fais le grand plongeon dans tes tiroirs et ressuscite cet objet mystÃ©rieux dont tu ne sais que faire. Qui sait, peut-Ãªtre quâ€™il deviendra le trÃ©sor dâ€™un autre ?

  Option 3 : Mets la main Ã  la pÃ¢te et crÃ©e un chef-dâ€™Å“uvre fait maison. Tes talents cachÃ©s sont sur le point dâ€™Ãªtre rÃ©vÃ©lÃ©s !

  ðŸŽ Rappel Important -> Ton identitÃ© doit resterâ€¦ un secret ! Chut, pas un mot !

  PrÃ©parons-nous Ã  partager des rires, des surprises et des souvenirs inoubliables. Que le meilleur cadeau gagneâ€¦ ou le plus hilarant ! ðŸ¤£

  Rendez-vous vendredi 22 dÃ©cembre midi sur le campus pour un Ã©change de cadeaux mÃ©morable !

  ðŸŒŸ Joyeux Secret Santa Ã  tous ! ðŸŒŸ

