# Required to connect to your outgoing mail server. Example for using gmail:
# gmail
SMTP_SERVER: smtp-mail.outlook.com
SMTP_PORT: 587
USERNAME: monadressemail@hotmail.fr
PASSWORD: "mon_mot_de_passe"

TIMEZONE: 'US/Pacific'

PARTICIPANTS:
  - Mathieu <5605@holbertonstudents.com>
  - Caroline <5692@holbertonstudents.com>
  - Cassandra <6724@holbertonstudents.com>
  - Christophe <6728@holbertonstudents.com>
  - JÃ©rÃ´me <6223@holbertonstudents.com>
  - Thomas <7560@holbertonstudents.com>
  - Sarah <7445@holbertonstudents.com>
  - Amandine <7427@holbertonstudents.com>
  - Alina <5689@holbertonstudents.com>
  - Omer <7434@holbertonstudents.com>
  - Lucie Delannay <3560@holbertonstudents.com>
  - Adrien <adrien.millot@holbertonschool.com>
  - FranÃ§ois <7458@holbertonstudents.com>
  - Mustapha Abourar <4250@holbertonstudents.com>
  - Olive <6705@holbertonstudents.com>
  - Annaik <annaik.meriadec@holbertonschool.com>
  - BenoÃ®t <benoit.denot@holbertonschool.com>
  - MathÃ©o <6221@holbertonstudents.com>
  - Cassandre <7467@holbertonstudents.com>
  - Carmen <7437@holbertonstudents.com>
  - SÃ©bastien <5610@holbertonstudents.com>
  - Rayane <5800@holbertonstudents.com>
  - LaÃ«titia <7488@holbertonstudents.com>
  - Alexis <7468@holbertonstudents.com>
  - Rich <7489@holbertonstudents.com>


# Warning -- if you mess this up you could get an infinite loop
DONT-PAIR:
  - Mathieu, Caroline   # are married
  - Cassandra, Christophe   # are married
  - LaÃ«titia, Thomas    # are in couple

# From address should be the organizer in case participants have any questions
FROM: Caro <fleur-a-fleur59@hotmail.fr>

# Both SUBJECT and MESSAGE can include variable substitution for the 
# "santa" and "santee"
SUBJECT: Tu es le secret santa de {santee}
MESSAGE: |

  ğŸ„ Ho Ho Ho, {santa} ! ğŸ…

  Câ€™est cette pÃ©riode magique de lâ€™annÃ©e oÃ¹ nos poches sont lÃ©gÃ¨res, mais nos cÅ“urs lourdsâ€¦ de rire ! PrÃ©pare-toi pour notre incroyable Secret Santa, oÃ¹ la rÃ¨gle dâ€™or est de ne pas dÃ©passer 5â‚¬. Oui, vous avez bien lu, moins que le prix d'une pinte de biÃ¨re au Gabo !

  Tu es le Secret Santa de {santee}

  Option 1 : Trouve quelque chose de mignon et joyeux Ã  moins de 5â‚¬. Un dÃ©fi pour ta crÃ©ativitÃ© et ton sens de lâ€™Ã©conomie !

  Option 2 : Fais le grand plongeon dans tes tiroirs et ressuscite cet objet mystÃ©rieux dont tu ne sais que faire. Qui sait, peut-Ãªtre quâ€™il deviendra le trÃ©sor dâ€™un autre ?

  Option 3 : Mets la main Ã  la pÃ¢te et crÃ©e un chef-dâ€™Å“uvre fait maison. Tes talents cachÃ©s sont sur le point dâ€™Ãªtre rÃ©vÃ©lÃ©s !

  ğŸ Rappel Important -> Ton identitÃ© doit resterâ€¦ un secret ! Chut, pas un mot !

  PrÃ©parons-nous Ã  partager des rires, des surprises et des souvenirs inoubliables. Que le meilleur cadeau gagneâ€¦ ou le plus hilarant ! ğŸ¤£

  Rendez-vous vendredi 22 dÃ©cembre midi sur le campus pour un Ã©change de cadeaux mÃ©morable !

  ğŸŒŸ Joyeux Secret Santa Ã  tous ! ğŸŒŸ



IMAGE_PATH: "image.png"
